apiVersion: v1
kind: Service
metadata:
  name: food-nutrition-service
spec:
  type: NodePort
  selector:
    app: food-nutrition
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30081